name: setup-uv
description: setup uv

inputs:
  version:
    description: uv version
    required: false
    default: "0.6.9"

runs:
  using: composite
  steps:
    - name: uv @ ${{ inputs.version }}
      uses: astral-sh/setup-uv@v5
      with:
        version: ${{ inputs.version }}

    - name: uv --version
      shell: bash
      run: uv --version
