name: uv python install
description: uv python install

inputs:
  working-directory:
    description: Working directory
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: uv python install
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: uv python install
