name: uv sync
description: uv sync

inputs:
  working-directory:
    description: Working directory
    required: false
    default: .

  uv_sync_cli_options:
    description: CLI options for uv sync
    required: false
    default: "--locked --all-extras"

runs:
  using: composite
  steps:
    - name: uv sync
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: uv sync ${{ inputs.uv_sync_cli_options }}
