name: uv sync
description: uv sync

inputs:
  sync_cli_options:
    description: CLI options for uv sync
    required: false
    default: "--locked --all-extras"

runs:
  using: composite
  steps:
    - name: uv sync
      shell: bash
      run: uv sync ${{ inputs.sync_cli_options }}
