name: uv python install
description: uv python install

inputs:
  directory:
    description: Working directory
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: uv python install
      shell: bash
      run: uv python install
