name: Test actions/uv_tool_intall

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/uv_python_install

      # installs tools like pyclean
      - uses: ./.github/actions/uv_tool_install

      - name: uv pip freeze
        run: uv pip freeze

      - name: "--version"
        run: uvx pyclean  --version

  python__matrix:
    needs: default
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    name: python @ ${{ matrix.python-version }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      - uses: percebus/github-actions-python/.github/actions/python_setup@main
        with:
          python-version: ${{ matrix.python-version }}

      # installs uv
      - uses: ./.github/actions/setup

      - uses: ./.github/actions/uv_tool_install

      - name: uv pip freeze
        run: uv pip freeze

      - name: "--version"
        run: uvx pyclean  --version

  uv__matrix:
    needs: default
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        uv-version:
          - "0.5.31"
          - "0.6.9"

    name: uv @ ${{ matrix.uv-version }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      - uses: ./.github/actions/setup
        with:
          version: ${{ matrix.uv-version }}

      - uses: ./.github/actions/uv_python_install

      - uses: ./.github/actions/uv_tool_install

      - name: uv pip freeze
        run: uv pip freeze

      - name: "--version"
        run: uvx pyclean  --version

  uv_tool__matrix:
    needs: default
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        uv-tool:
          - pyclean
          - pypyr

    name: "uv tool install: ${{ matrix.uv-tool }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/uv_python_install

      - uses: ./.github/actions/uv_tool_install
        with:
          requirements-file: ./assets/uv_tool/${{ matrix.uv-tool }}/requirements.uv.tool.txt

      - name: uv pip freeze
        run: uv pip freeze

      - name: "${{ matrix.uv-tool }} --version"
        run: uvx ${{ matrix.uv-tool }} --version
