name: Test actions/uv_sync

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      - uses: percebus/github-actions-uv/.github/actions/setup@main

      - name: uv python install
        run: uv python install

      # installs tools like pyclean
      - uses: ./.github/actions/uv_sync

      - name: uv pip freeze
        run: uv pip freeze
