name: Test actions/uv_python_install

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      - uses: ./.github/actions/setup

      # installs tools like pyclean
      - uses: ./.github/actions/uv_python_install

      # TODO venv?

  python__matrix:
    needs: default
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-versions:
          - "3.12.x"
          - "3.13.x"
          - "3.x"

    name: python @ ${{ matrix.python-versions }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      - uses: ./.github/actions/setup

      - uses: ./.github/actions/uv_python_install
        with:
          directory: assets/uv_python/${{ matrix.python-versions }}

      # TODO venv?
